export const title = "Virtual Attribute";
export const endpoint = "virtual-attribute";
export const columns = [
  {
    name: "name",
    required: true,
    label: "Name",
    align: "left",
    field: "name",
    sortable: true,
    type: "string",
    size: "col-6",
    showOnForm: true,
  },
  {
    name: "label",
    required: false,
    label: "Label",
    align: "left",
    field: "label",
    sortable: true,
    type: "string",
    size: "col-6",
    showOnForm: true,
  },
  {
    name: "field",
    required: false,
    label: "Field",
    align: "left",
    field: "field",
    sortable: true,
    type: "string",
    size: "col-6",
    showOnForm: true,
    formRequired: false,
  },
  {
    name: "size",
    required: false,
    label: "Size",
    align: "left",
    field: "size",
    sortable: true,
    type: "string",
    size: "col-6",
    formRequired: false,
    showOnForm: true,
  },
  {

    name: "order",
    required: false,
    label: "Order",
    align: "left",
    field: "order",
    sortable: true,
    type: "integer",
    size: "col-6",
    formRequired: false,
    showOnForm: true,
  },
  {

    name: "type",
    required: false,
    label: "Type",
    align: "left",
    field: "type",
    sortable: true,
    type: "select",
    size: "col-6",
    formRequired: false,
    showOnForm: true,
    options: "string|number|textarea|select|date|time|currency|reference"
  },
  {
    name: "virtual_model_id",
    required: false,
    label: "Virtual_model_id",
    align: "left",
    field: "virtual_model_id",
    sortable: true,
    type: "unsignedBigInteger",
    size: "col-12",
    showOnForm: false,
  },
  {
    name: "tab",
    required: false,
    label: "Tab",
    align: "left",
    field: "tab",
    sortable: true,
    type: "string",
    size: "col-12",
    showOnForm: false,
  },
  {
    name: "is_required",
    required: false,
    formRequired: true,
    label: "Is Required",
    align: "left",
    field: "is_required",
    sortable: true,
    type: "boolean",
    size: "col-3",
    showOnForm: true,
  },
  {
    name: "is choices",
    required: false,
    formRequired: true,
    label: "Is choices",
    align: "left",
    field: "is_choices",
    sortable: true,
    type: "boolean",
    size: "col-3",
    showOnForm: true,
  },
  {
    name: "Show on form",
    required: false,
    formRequired: true,
    label: "Show on form",
    align: "left",
    field: "show_on_form",
    sortable: true,
    type: "boolean",
    size: "col-3",
    showOnForm: true,
  },
  {
    name: "is_choices",
    required: false,
    label: "Is_choices",
    align: "left",
    field: "is_choices",
    sortable: true,
    type: "boolean",
    size: "col-6",
    showOnForm: false,
  },
  {
    name: "options",
    required: false,
    label: "Options",
    align: "left",
    field: "options",
    sortable: true,
    type: "textarea",
    size: "col-12",
    showOnForm: true,
    needAttribute: "is_choices"
  },
  {
    name: "reference",
    renderIf: true,
    renderIfField: 'type',
    renderIfValue: 'reference',
    required: false,
    label: "Reference",
    align: "left",
    field: "reference",
    sortable: true,
    type: "referenceSSR",
    endpoint: "virtual-attribute/select",
    select: "name",
    size: "col-6",
    updateOn: "field_reference",
    formRequired: false,
    showOnForm: true,
  },
  {
    name: "field_reference",
    renderIf: true,
    renderIfField: 'type',
    renderIfValue: 'reference',
    required: false,
    label: "Field Reference",
    align: "left",
    field: "field_reference",
    sortable: true,
    type: "select",
    endpoint: "virtual-attribute/attribute",
    select: "name",
    size: "col-6",
    formRequired: false,
    showOnForm: true,
    hasCustomOption: true
  },
];

export const visibleColumns = [
  'name',
  'field',
  'type',
  'size',
  'order',
  'label',
];